export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/sign'
export const NOTIFICATION = '/notifications'
export const POLICIES_ROUTE = '/policies'
export const CLAIMS_ROUTE = '/claims'
export const PAYMENTS_ROUTE = '/payments'
export const PERSONAL_ROUTE = '/personal-info'

export const EMPLOYEE_HOME_ROUTE = '/home'
export const EMPLOYEE_CUSTOMER_LIBRARY_ROUTE = '/customer'
export const EMPLOYEE_NEW_CUSTOMER = '/new-customer'
export const EMPLOYEE_NEW_CUSTOMER_POLICY_SELECT = '/new-customer/policy-select'
export const EMPLOYEE_NEW_CUSTOMER_VALIDATION = '/new-customer/validation'
export const EMPLOYEE_NEW_CUSTOMER_APPROVE = '/approve'

export const EMPLOYEE_HOME_CLAIMS = '/home/claims'
export const EMPLOYEE_HOME_PAYMENTS = '/home/payments'
export const EMPLOYEE_HOME_NOTIFICATIONS = '/home/notifications'