export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/sign'
export const NOTIFICATION = '/notifications'
export const POLICIES_ROUTE = '/policies'
export const CLAIMS_ROUTE = '/claims'
export const PAYMENTS_ROUTE = '/payments'
export const PERSONAL_ROUTE = '/personal-info'

export const EMPLOYEE_HOME_ROUTE = '/home'
export const EMPLOYEE_CUSTOMER_LIBRARY_ROUTE = '/customer'
export const EMPLOYEE_NEW_CUSTOMER = '/new-customer'